### ISSUE TITLE
[Bug] Information on Bait set lost when submitting an order through an excel sheet

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/orderportal#16]
In [Ticket #982690](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=64879) the customer complaints that when they try to submit an order with panel analysis using an excel sheet, the information on `Bait set` is lost for each case and they are forced to manually select it in the order portal for every single case in the order. Tested submitting the order form sent by the customer and replicated the issue.

**Comment by islean** [comment]
Seems as if FASTQ orders do not set Bait set/Capture kit in the old order portal (but does so in the new). SA and I created a PR which addresses this which is linked.
