### ISSUE TITLE
[Feature request] Panel field should be validated for existing panels

### ISSUE THREAD

**Issue by beatrizsavinhas** [Clinical-Genomics/orderportal#17]
A customer placed an order with contained a typo in the panel for a case. As a consequence, the case could not be uploaded and panel information is necessary to calculate some of the metrics presented in the delivery report.
The panel field should be validated against the list of existing panels to avoid issues like this.

**Comment by islean** [comment]
This is fixed in https://github.com/Clinical-Genomics/clinical-genomics-ui/pull/382.
