### ISSUE TITLE
Remove the +++ in the headings to make the guide more readable

### ISSUE THREAD

**Issue by patrikgrenfeldt** [Clinical-Genomics/orderportal#2]
I feel that the +++ catch my eye in a way that makes the text hard to read, can we remove them?

**Comment by emiliaol** [comment]
We'd like something to catch your eye at those specific points. Any idea as to what we should use instead?

**Comment by patrikgrenfeldt** [comment]
Removed the +++ to improve the readability. To further increase readability and in some sense regain what was achieved with the +++ we could write some descriptions directly under the headings to make the headings stand out.
