### ISSUE TITLE
HELP - CAN NOT PLACE ORDER MANUALLY

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/orderportal#3]
I am trying to place an order in the order portal manually but I am not able to do that.
- can not add families - only samples
- can not add affected / non affected 
etc  ....
![bild](https://user-images.githubusercontent.com/17139607/46402019-e6255800-c6fe-11e8-9922-9a75205a34d3.png)

**Comment by patrikgrenfeldt** [comment]
Hi, 

There seems to be an issue with the "Add Sample" button, it should not be usable before the Order-head has been saved. To avoid the problem, please try to create a new order where you select "Type" before going on to add samples.

BR
Patrik Grenfeldt

**Comment by KickiLagerstedt** [comment]
OK - it seemed to work!
Thank You!

**Comment by patrikgrenfeldt** [comment]
The button "Add sample" should now become visible when you have selected what type of order you want
