### ISSUE TITLE
AKUT!!! Impossible to import j-son files

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/orderportal#7]
We are unable to import our j-son files (worked last week)

Error message:
![image](https://user-images.githubusercontent.com/17139607/134526401-aa225c5a-17ad-43fc-b9e0-e3006edaef75.png)

**Comment by vwirta** [comment]
I add @annagellerbring to the thread to keep her in the loop.

Do you get this error for several json files, or just one specific?

**Comment by dnil** [comment]
There was a pending PR for this, where synopsis changes to the expected str rather than str[] a but I suppose we don't expect to deploy it until we have confirmation of the next StarLIMS delivery with that fixed? I was going to help review at some point but I lost track - sorry!😳

**Comment by dnil** [comment]
Here: https://github.com/Clinical-Genomics/scout/issues/2859
If StarLIMS still does synopsis as str[] etc according to the old spec that will likely need to be reverted and await their release/fix until it is deployed on cg.

**Comment by dnil** [comment]
Ahem, here https://github.com/Clinical-Genomics/cg/pull/1191

**Comment by annagellerbring** [comment]
@patrikgrenfeldt can you look into this ASAP?

**Comment by patrikgrenfeldt** [comment]
Yes I am currently looking into this

**Comment by patrikgrenfeldt** [comment]
The quick workaround that should work immediately is to edit the json and remove the characters "[" and "]" on the line(s) of '"synopsis":'

**Comment by KickiLagerstedt** [comment]
Hej Patrik!

???
Skulle jag förstå vad du menade nu?? Hur gör jag när jag ska editera j-son???

// Kicki

Från: Patrik Grenfeldt ***@***.***>
Skickat: den 24 september 2021 08:56
Till: Clinical-Genomics/orderportal ***@***.***>
Kopia: Kristina Lagerstedt ***@***.***>; Author ***@***.***>
Ämne: Re: [Clinical-Genomics/orderportal] AKUT!!! Impossible to import j-son files (#7)


The quick workaround that should work immediately is to edit the json and remove the characters "[" and "]" on the line(s) of '"synopsis":'

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FClinical-Genomics%2Forderportal%2Fissues%2F7%23issuecomment-926391048&data=04%7C01%7Ckristina.lagerstedt%40ki.se%7C38c889599abc47f6eb1a08d97f285790%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637680633507103735%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kSNMcZZSTSfZBTwlwUpyFqk5tqIP0EPV2SnVjEy9nuQ%3D&reserved=0>, or unsubscribe<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAECYPF22OZK4BAUNGRRB3S3UDQOHJANCNFSM5ET2QNYA&data=04%7C01%7Ckristina.lagerstedt%40ki.se%7C38c889599abc47f6eb1a08d97f285790%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637680633507113736%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m%2FDA0XzNJ%2FVN45Sf3WQz%2BYdBCHbgzWKKsduNbrQjnr8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ckristina.lagerstedt%40ki.se%7C38c889599abc47f6eb1a08d97f285790%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637680633507123729%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kLQs0U6F4Kw7PjuyyKsoQVlizjIZBiWDyo1Y%2BZmj%2FP0%3D&reserved=0> or Android<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ckristina.lagerstedt%40ki.se%7C38c889599abc47f6eb1a08d97f285790%7Cbff7eef1cf4b4f32be3da1dda043c05d%7C0%7C0%7C637680633507133728%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gmVntDCV9ZTdQxNmJV3nWMVV0bc9E0ErJ%2BOkJYsMFNQ%3D&reserved=0>.



När du skickar e-post till Karolinska Institutet (KI) innebär detta att KI kommer att behandla dina personuppgifter. Här finns information om hur KI behandlar personuppgifter<https://ki.se/medarbetare/integritetsskyddspolicy>.


Sending email to Karolinska Institutet (KI) will result in KI processing your personal data. You can read more about KI's processing of personal data here<https://ki.se/en/staff/data-protection-policy>.

**Comment by KickiLagerstedt** [comment]
Lyckades öppna j-son i något slags program och har tagit bort hakparanteser... 
Hoppas att dessa ordrar har gått in...

// Kicki

**Comment by annagellerbring** [comment]
Hej Kicki! 

Du är grym :) ordrarna är inne!

/Anna

**Comment by KickiLagerstedt** [comment]
Hero lägger orders för de myeloida panelerna nu... 

Vi försöker så gott vi kan här  ;=)

**Comment by patrikgrenfeldt** [comment]
I have made a patch to the production system that will from now on allow both variants of synopsis, either as a list (old way) or as a string (new way).

**Comment by patrikgrenfeldt** [comment]
Closing, please reopen if any issues still remain
