### ISSUE TITLE
Network error x3

### ISSUE THREAD

**Issue by KickiLagerstedt** [Clinical-Genomics/orderportal#8]
To whom it may concern,

I am not able to place my orders in the orderportal - the error message I get i "Network error". I have tried x3

![image](https://user-images.githubusercontent.com/17139607/137265233-681cf95f-6b33-4151-bd51-492a00f9505a.png)

I have also checked in the "items"-folder - the order is not there

![image](https://user-images.githubusercontent.com/17139607/137265428-19a67f95-7bca-4b04-a764-e141bbdfab62.png)

**Comment by patrikgrenfeldt** [comment]
The connection to the LIMS and ticketing was in error. This was fixed Oct 14th. Closing.
